@startuml
left to right direction
skinparam packageStyle rectangle
actor 管理员 #Green
actor 用户 #yellow
rectangle 火车订票系统用例图{
    (修改票务信息)..[#write](订票)
    (修改车次信息)..[#write](改签)
    (系统管理)..[#write](查看车次信息)
    管理员-->(修改用户信息)
    管理员-->(实时信息提示)
    管理员-->(修改票务信息)
    管理员-->(修改车次信息)
    管理员-->(系统管理)
    (修改用户信息)<--用户
    (实时信息提示)<--用户
    (订票)<--用户
    (查看车次信息)<--用户
    (退票)<--用户
    (改签)<--用户
}

footer 201810414412 黄海峰
@enduml