@startuml
'https://plantuml.com/sequence-diagram

class Account{
    +userdatall
    +admindatall
}

class User{
    +name
    +password
    +IDcard

    +getprice()
    +getdate()
    +getnumber()
    +getplace()
    +bookingtecket()
    +changebooking()
    +returnticket()
}

class Admin{
    +name
    +password
    +changeticket()
}

class Order{
    +username
    +userId
    +bookingtecket
}

class TicketSystem{
    +cancel()
    +display()
    +recordticket()
    +recordorder()
    +displayticket()
    +displayorder()
    +update()
    +searchticket()
    +searchorder()
}

class Ticket{
    +price
    +date
    +number
    +price
}

Account <|-- User
Account <|-- Admin
User --> TicketSystem
Admin --> TicketSystem
TicketSystem --> Order
TicketSystem --> Ticket

footer 201810414412 黄海峰
@enduml